// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"BE-Project/controller"
	"BE-Project/helper"
	"BE-Project/middleware"
	"BE-Project/repository"
	"BE-Project/service"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitProject(db *gorm.DB) controller.ProjectController {
	projectRepository := repository.NewProjectRepository(db)
	projectService := service.NewProjectService(projectRepository)
	jwtService := service.NewJWTService()
	logger := logrus.New()
	log := helper.NewLog(logger)
	projectController := controller.NewProjectController(projectService, jwtService, log)
	return projectController
}

func InitJWTMiddleware() middleware.AuthorizeJWTMiddleware {
	jwtService := service.NewJWTService()
	authorizeJWTMiddleware := middleware.NewAuthorizeJWTMiddleware(jwtService)
	return authorizeJWTMiddleware
}

// injector.go:

var jwtMiddlewareSet = wire.NewSet(service.NewJWTService, middleware.NewAuthorizeJWTMiddleware)

var projectSet = wire.NewSet(logrus.New, helper.NewLog, repository.NewProjectRepository, service.NewProjectService, service.NewJWTService, controller.NewProjectController)
